import { beforeEach, describe, expect, it } from 'vitest'
import { createPinia, setActivePinia } from 'pinia'
import { useTaskSelectionStore, type SelectionRequest } from '../taskSelection'
const media: SelectionRequest = { kind: 'media', gid: 'a' }
const bt: SelectionRequest = { kind: 'bt', gid: 'b' }

describe('selection queue', () => {
  beforeEach(() => setActivePinia(createPinia()))
  it('waits for readiness and deduplicates automatic requests', () => {
    const store = useTaskSelectionStore()
    store.register(media.gid, true)
    store.reconcile([], [])
    expect(store.queue).toEqual([])
    store.reconcile([media], [media])
    store.reconcile([media], [media])
    expect(store.queue).toEqual([media])
    store.present()
    store.reconcile([media], [media])
    expect(store.current).toEqual(media)
    expect(store.queue).toEqual([])
  })
  it('preserves manual and restored selection policies', () => {
    const store = useTaskSelectionStore()
    store.register(bt.gid, false)
    store.reconcile([bt, media], [bt, media])
    expect(store.pending).toHaveLength(2)
    expect(store.queue).toEqual([])
    store.request(bt)
    store.present()
    expect(store.current).toEqual(bt)
  })
  it('retains the active request until the closing animation completes', () => {
    const store = useTaskSelectionStore()
    store.request(bt)
    store.request(media)
    store.present()
    store.close()
    store.present()
    expect(store.current).toEqual(bt)
    expect(store.visible).toBe(false)
    store.afterLeave()
    store.present()
    expect(store.current).toEqual(media)
  })
  it('does not reopen deferred tasks, but allows explicit selection', () => {
    const store = useTaskSelectionStore()
    store.register(media.gid, true)
    store.reconcile([media], [media])
    store.present()
    store.close()
    store.afterLeave()
    store.reconcile([media], [media])
    store.request(media, true)
    expect(store.queue).toEqual([])
    store.request(media)
    store.present()
    expect(store.current).toEqual(media)
  })
  it('closes invalid requests and removes deleted queued tasks', () => {
    const store = useTaskSelectionStore()
    store.request(media)
    store.request(bt)
    store.present()
    store.reconcile([], [])
    expect(store.phase).toBe('closing')
    expect(store.current).toEqual(media)
    expect(store.queue).toEqual([])
  })
  it('clears registration and pending state after deletion', () => {
    const store = useTaskSelectionStore()
    store.register(bt.gid, true)
    store.reconcile([bt], [bt])
    store.forget([bt.gid])
    expect(store.pending).toEqual([])
    expect(store.queue).toEqual([])
    store.reconcile([bt], [bt])
    expect(store.queue).toEqual([])
  })
})
